//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolastaDruidClass.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolastaDruidClass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DruidSavingthrowProficiency	02e96b5d-c92d-4869-a9c1-ff12bf15b488
        ///DruidProficiencies	5b0c5413-79ae-4898-b993-85cf3619a938
        ///DruidArmorProficiencies	eb0d5b55-b878-4828-aaca-e4aa95a2a9db
        ///DruidClassSkillPointPool	8f2cb82d-6bf9-4a72-a3e1-286a1e2b5662
        ///DruidToolsProficiency	c387e9c8-3a38-4c00-8c1a-d7419b7dbb59
        ///DruidSpelllist	19ef0624-ede3-4612-b636-6479dd8f4e2e
        ///DruidCastingAbility	64e9ce25-cbbc-4ff2-9fd2-0e4ad1d32a67
        ///DruidRitualSpellcasting	8e979528-e1b1-44df-9ae2-a09ab1ba6c21
        ///WildshapeWolfBiteAttack	67533c2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string blueprints {
            get {
                return ResourceManager.GetString("blueprints", resourceCulture);
            }
        }
    }
}
